### ISSUE TITLE
问几个关于文章的问题

### ISSUE THREAD

**Issue by jsrdcht** [7eu7d7/RobustDet#6]
3.2.1 节，clean images and adversarial images对网络的梯度，为什么entanglement被认为是不好的？我觉得负相关是不对，正相关也有问题吗？

**Comment by 7eu7d7** [comment]
梯度向量在一个高度非线性的高维空间，两个向量夹角的正负不能直接说明是否有协同关系，只能说明两个梯度有影响，会相互干扰。这个梯度的分析是基于前面loss变化已经得出冲突结论的，为了给冲突从梯度层面找一个解释。如果两种样本继续学习还有协同关系那肯定说明模型是没收敛的，但这个实验是在已经收敛的模型上进行的，所以在这种高度非线性的高维空间里梯度夹角是锐角并不能推论出有协同关系。有entanglement可以说明有相互影响，但协同还是冲突不确定，不过没有entanglement就肯定没有冲突。
